// startup.c code based off of LPC824 example 
// https://github.com/jdesbonnet/LPC824-barechip-Blinky/blob/master/example/src/cr_startup_lpc82x.c


// The following symbols are constructs generated by the linker, indicating
// the location of various points in the "Global Section Table". This table is
// created by the linker via the Code Red managed linker script mechanism. It
// contains the load address, execution address and length of each RW data
// section and the execution and length of each BSS (zero initialized) section.
extern unsigned int __data_start__;
extern unsigned int __data_end__;
extern unsigned int __bss_start__;
extern unsigned int __bss_end__;

extern void _vStackTop(void);


#define WEAK __attribute__ ((weak))
#define ALIAS(f) __attribute__ ((weak, alias(#f)))


// weak/aliased default handler declaration 
void reset_handler(void);
WEAK void NMI_Handler(void);
WEAK void HardFault_Handler(void);
WEAK void SVC_Handler(void);
WEAK void PendSV_Handler(void);
WEAK void SysTick_Handler(void);
WEAK void default_handler(void);


// weak/aliased IRQ handler declaration
void SPI0_IRQHandler(void) ALIAS(default_handler);
void SPI1_IRQHandler(void) ALIAS(default_handler);
void UART0_IRQHandler(void) ALIAS(default_handler);
void UART1_IRQHandler(void) ALIAS(default_handler);
void UART2_IRQHandler(void) ALIAS(default_handler);
void I2C1_IRQHandler(void) ALIAS(default_handler);
void I2C0_IRQHandler(void) ALIAS(default_handler);
void SCT_IRQHandler(void) ALIAS(default_handler);
void MRT_IRQHandler(void) ALIAS(default_handler);
void CMP_IRQHandler(void) ALIAS(default_handler);
void WDT_IRQHandler(void) ALIAS(default_handler);
void BOD_IRQHandler(void) ALIAS(default_handler);
void FLASH_IRQHandler(void) ALIAS(default_handler);
void WKT_IRQHandler(void) ALIAS(default_handler);
void ADC_SEQA_IRQHandler(void) ALIAS(default_handler);
void ADC_SEQB_IRQHandler(void) ALIAS(default_handler);
void ADC_THCMP_IRQHandler(void) ALIAS(default_handler);
void ADC_OVR_IRQHandler(void) ALIAS(default_handler);
void DMA_IRQHandler(void) ALIAS(default_handler);
void I2C2_IRQHandler(void) ALIAS(default_handler);
void I2C3_IRQHandler(void) ALIAS(default_handler);
void PIN_INT0_IRQHandler(void) ALIAS(default_handler);
void PIN_INT1_IRQHandler(void) ALIAS(default_handler);
void PIN_INT2_IRQHandler(void) ALIAS(default_handler);
void PIN_INT3_IRQHandler(void) ALIAS(default_handler);
void PIN_INT4_IRQHandler(void) ALIAS(default_handler);
void PIN_INT5_IRQHandler(void) ALIAS(default_handler);
void PIN_INT6_IRQHandler(void) ALIAS(default_handler);
void PIN_INT7_IRQHandler(void) ALIAS(default_handler);



// Functions to carry out the initialization of RW and BSS data sections. These
// are written as separate functions rather than being inlined within the
// ResetISR() function in order to cope with MCUs with multiple banks of
// memory.
__attribute__ ((section(".after_vectors")))
void data_init(unsigned int rom_start, unsigned int start, unsigned int len){
    unsigned int *pulDest = (unsigned int*) start;
    unsigned int *pulSrc = (unsigned int*) rom_start;
    unsigned int loop;
    for (loop = 0; loop < len; loop = loop + 4){
        *pulDest++ = *pulSrc++;
    }
}

__attribute__ ((section(".after_vectors")))
void bss_init(unsigned int start, unsigned int len){
    unsigned int *pulDest = (unsigned int*) start;
    unsigned int loop;
    for (loop = 0; loop < len; loop = loop + 4){
        *pulDest++ = 0;
    }
}


extern int main(void);


// include the vector table as defined in vectors.inc
#include "vectors.inc"

#include "LPC8xx.h"

// todo: move to a better location (config file?)
#define EXTERNAL_OSCILLATOR
// Reset entry point for your code.
// Sets up a simple runtime environment and initializes the C/C++
// library.
__attribute__ ((section(".after_vectors")))
void reset_handler(void){

    // External Clock Setup

    // configuring PIO0_9, PIO0_8 to disable everything
    LPC_IOCON->PIO0_9 = 0x00;
    LPC_IOCON->PIO0_8 = 0x00;

    // enable XTALIN, XTALOUT
    LPC_SWM->PINENABLE0 ^= 0b11000000;

    // disable oscillator bypass, set freq range to 1 - 20 Mhz
    LPC_SYSCON->PDRUNCFG = 0x00;


    // Copy .data to RAM     
    unsigned int LoadAddr, ExeAddr, SectionLen;
    unsigned int *SectionTableAddr; 

    // Copy data section base address
    SectionTableAddr = &__data_start__;

    // Copy the data sections from flash to SRAM.
    while (SectionTableAddr < &__data_end__) {
        LoadAddr = *SectionTableAddr++;
        ExeAddr = *SectionTableAddr++;
        SectionLen = *SectionTableAddr++;
        data_init(LoadAddr, ExeAddr, SectionLen);
    }
    // At this point, SectionTableAddr = &__bss_section_table;
    // Zero fill the bss segment
    while (SectionTableAddr < &__bss_end__) {
        ExeAddr = *SectionTableAddr++;
        SectionLen = *SectionTableAddr++;
        bss_init(ExeAddr, SectionLen);
    }

    main();
    
    while(1);


}

// Default expection or interrupt handler
__attribute__ ((section(".after_vectors")))
void default_handler(void){
    for(;;);
}


